### ISSUE TITLE
js und css Links für Offline Entwicklung umstellen (macht aku)

### ISSUE THREAD

**Issue by digital-codes** [okfde/dev.codefor.de#19]
In den Partials in themes/hugo-cfg/layouts/partials sind absolute Links auf https://dev.codefor.de, dadurch kann man nicht offline entwickeln. Vorschlag: ersetzen durch Filesystems links:

<link rel="icon" type="image/png" href="/images/favicon.png" />
statt
link rel="icon" type="image/png" href="https://dev.codefor.de/images/favicon.png" />

etc. für alle Bilder, css, js und fonts.

**Comment by joliyea** [comment]
Aku

**Comment by ubergesundheit** [comment]
Funktioniert würde ich sagen. #28 #30
