### ISSUE TITLE
Karte

### ISSUE THREAD

**Issue by digital-codes** [okfde/dev.codefor.de#24]
Wie wärs mit sowas?
![labmap](https://user-images.githubusercontent.com/34965919/73590139-1e010300-44df-11ea-8dc1-b768ca886f3e.png)

**Comment by ubergesundheit** [comment]
Sieht gut aus, eine andere Idee wäre es, auf eine Rasterkarte komplett zu verzichten und nur eine Rudimentäre Deutschlandkarte in SVG (zb mit d3) zu machen, das hätte den Vorteil, dass wir mapbox nicht bezahlen müssen.
