### ISSUE TITLE
Lab-Seite (Übersicht mit Karte und Liste)

### ISSUE THREAD

**Issue by joliyea** [okfde/dev.codefor.de#4]
- Die Lab-Seite sollte eine Karte enthalten mit Markern der einzelnen Labs.
- Labels mit Städten aber nur beim Hovern.
- Eine Liste aller Labs, die auf eine entsprechende Detailseite für jedes Lab linkt.
- Buttons / Links: "Gründe dein eigenes Lab." bzw. "Mitmachen ohne Lab"

**Comment by wagnerpeer** [comment]
Ist dieser Issue noch aktuell?

**Comment by wagnerpeer** [comment]
Neue Seite beinhaltet angeforderte Aenderungen.
